In [2]:
import numpy as np

In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [69]:
#1d
l = [1,321,31,24,13,4,32,4,3,413,413,4]
print(l)

#2D
l1 = [
    [1,2,2],
    [3,4,5],
    [5,6,7],
]
print(l1)
#3D
l2 = [
    [
        [1,2,3],
        [4,5,6],
        [6,7,8],
    ],
    [
        [9,8,7],
        [7,6,4],
        [4,5,6],
    ],
]
print(l2)

[1, 321, 31, 24, 13, 4, 32, 4, 3, 413, 413, 4]
[[1, 2, 2], [3, 4, 5], [5, 6, 7]]
[[[1, 2, 3], [4, 5, 6], [6, 7, 8]], [[9, 8, 7], [7, 6, 4], [4, 5, 6]]]


In [70]:
a1 = np.array(l)
a2 = np.array(l1)
a3 = np.array(l2)

In [6]:
print(a1,"\n\n\n",a2,"\n\n\n\n",a3)

[  1 321  31  24  13   4  32   4   3 413 413   4] 


 [[1 2 2]
 [3 4 5]
 [5 6 7]] 



 [[[1 2 3]
  [4 5 6]
  [6 7 8]]

 [[9 8 7]
  [7 6 4]
  [4 5 6]]]


In [7]:
print(type(a1))

<class 'numpy.ndarray'>


In [8]:
a1.ndim

1

In [9]:
a2.ndim

2

In [10]:
a3.ndim

3

In [11]:
a1.shape

(12,)

In [12]:
a2.shape

(3, 3)

In [13]:
a3.shape

(2, 3, 3)

In [16]:
print(type(a2))

<class 'numpy.ndarray'>


In [23]:
l2 = [
    [
        [1,2,3],
        [4,5,6],
        [6,7,8],
    ],
    [
        [9,8,7],
        [7,6,4],
        [4,5,6],
    ],
]

In [28]:
l4=np.array(l2,dtype=complex)

In [29]:
print(type(l4))

<class 'numpy.ndarray'>


In [30]:
l4.ndim

3

In [31]:
l4

array([[[1.+0.j, 2.+0.j, 3.+0.j],
        [4.+0.j, 5.+0.j, 6.+0.j],
        [6.+0.j, 7.+0.j, 8.+0.j]],

       [[9.+0.j, 8.+0.j, 7.+0.j],
        [7.+0.j, 6.+0.j, 4.+0.j],
        [4.+0.j, 5.+0.j, 6.+0.j]]])

In [41]:
a = np.array([[12,3,3],[33,4,43],[454,34,3]],dtype=np.int64)

In [42]:
a.shape

(3, 3)

In [43]:
a

array([[ 12,   3,   3],
       [ 33,   4,  43],
       [454,  34,   3]], dtype=int64)

In [44]:
a.itemsize

8

In [45]:
a.size

9

In [46]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [51]:
a1/11

array([[0.09090909, 0.18181818, 0.27272727],
       [0.36363636, 0.45454545, 0.54545455],
       [0.63636364, 0.72727273, 0.81818182]])

In [53]:
a1+55

array([[56, 57, 58],
       [59, 60, 61],
       [62, 63, 64]])

In [54]:
a2**2

array([[ 1,  4,  4],
       [ 9, 16, 25],
       [25, 36, 49]], dtype=int32)

In [55]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
a2

array([[1, 2, 2],
       [3, 4, 5],
       [5, 6, 7]])

In [58]:
a1+a2   #elementwise addition

array([[ 2,  4,  5],
       [ 7,  9, 11],
       [12, 14, 16]])

In [60]:
a1-a2   #elementwise subtraction

array([[0, 0, 1],
       [1, 1, 1],
       [2, 2, 2]])

In [62]:
a1*a2 #elementwise multiplication

array([[ 1,  4,  6],
       [12, 20, 30],
       [35, 48, 63]])

In [63]:
print(a1)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 2]
 [3 4 5]
 [5 6 7]]


In [65]:
a1@a2  #matrix multiplication

array([[ 22,  28,  33],
       [ 49,  64,  75],
       [ 76, 100, 117]])

In [66]:
a1.dot(a2)

array([[ 22,  28,  33],
       [ 49,  64,  75],
       [ 76, 100, 117]])

In [71]:
a1

array([  1, 321,  31,  24,  13,   4,  32,   4,   3, 413, 413,   4])

In [72]:
a1[5:8]

array([ 4, 32,  4])

In [73]:
a2

array([[1, 2, 2],
       [3, 4, 5],
       [5, 6, 7]])

In [80]:
a2[2][2]

7

In [81]:
a2[1][2]

5

In [83]:
a2[2][1:3]

array([6, 7])

In [93]:
a3[1][2][0:2]

array([4, 5])

In [94]:
s ="Hello World"

In [96]:
s[4:-2:1]

'o Wor'

In [100]:
s[:-3:1]

'Hello Wo'

In [99]:
s[::1]

'Hello World'